### ISSUE TITLE
Exception not handled correctly

### ISSUE THREAD

**Issue by monamimani** [GameTechDev/PracticalVulkan#3]
I have seen at least at 2 places that the try/catch block are wrong.
In SampleCommon::AcquireImage and SampleCommon::FinishFrame there is something like this.

```
    vk::Result result = vk::Result::eSuccess;
    try {
      result = GetDevice().acquireNextImageKHR( *current_frame.Swapchain->Handle, 3000000000, *current_frame.FrameResources->ImageAvailableSemaphore, vk::Fence(), &current_frame.SwapchainImageIndex );
    } catch( ... ) {
      if( vk::Result::eErrorOutOfDateKHR == result ) {
        OnWindowSizeChanged();
      } else {
        throw;
      }
    }
```

The thing is that if acquireNextImageKHR throw and exception result will never be assigned and in the catch the if statement will always be false. There is a similar issue in FinishFrame and maybe more in the code base.

the solution is to have a catch block like this

```
  catch (const vk::OutOfDateKHRError& /*exception*/)
  {
    recreateSwapchain();
    return;
  }
```

**Comment by Ekzuzy** [comment]
Thanks for pointing this out!

**Comment by Ekzuzy** [comment]
I've modified the code responsible for handling the `vkAcquireNextImageKHR()` and `vkQueuePresentKHR()` functions. But eventually it turned out that, in this case, not using vulkan.hpp exceptions gives a much more readable code.

This is true especially for the `queuePresentKHR()` function in which I want both `eSuboptimalKHR` (which is a success) and `eErrorOutOfDateKHR` return values to cause swapchain recreation. With exceptions enabled, in case of the `eSuboptimalKHR` value I'd need to check the return value while for the `eErrorOutOfDateKHR` I'd need to catch an exception. Without exceptions the code is more unified and readable.
